const SELECTORS = {
  login: {
    username: "#UserName",
    password: "#Password",
    submit: "#btnSubmit",
  },
  captcha: {
    image: "#captchaImage",
    input: "#captchaInput",
  },
  smartForm: {
    continue: "#content > div > div.page-content-inner > div.row > div > div > div > div > div.form-actions.fluid > div > div.col-md-7.text-right > div > a",
    applicationsTable: "#gridViewSearch > div > table",
    firstApplicationRow: "tbody > tr:first-child",
    applicationIdCell: "td:nth-child(1)",
    passportNumberCell: "td:nth-child(3)",
  },
  agreement: {
    continue: "#content > div > div.page-content-inner > div.row > div > div > div.portlet-body.form > div > div.form-actions.fluid.right > div > div > a.btn.green",
  },
  electronicAgreement: {
    continue: "#content > div > div.page-content-inner > div.row > div > div > div.portlet-body.form > div > div.form-actions.fluid.right > div > div > a.btn.green",
  },
  visaInfoLogin: {
    captchaImage: "#imgCaptcha",
    captchaInput: "#Captcha",
    processingStatus:
      "#content > div > div.page-content-inner > div.row > div > div > div.portlet-title > div > div > span",
    resumeCommit:
      "#content > div > div.page-content-inner > div.row > div > div > div.portlet-body.form > form > div.form-actions.fluid.right > div > div > button",
  },
  visaInfoLoggedIn: {
    sponsorFullName:
      "#content > div > div.page-content-inner > div.portlet.box.mofa-green > div.portlet-body.form > div > form > div:nth-child(2) > div:nth-child(2)",
  },
  traditionalApp: {
    cookieClose:
      "body > div.container-cookie-banner.alert.text-center.cookiealert.show > div.cookie-header > div.cursor-pointer > svg",
    visaType: "#VisaKind",
    nationality: "#NATIONALITY",
    embassy: "#EmbassyCode",
    numberOfEntries: "#NUMBER_OF_ENTRIES",
    visaValidity: "#Number_Entry_Day",
    residencePeriod: "#RESIDENCY_IN_KSA",
    firstNameAr: "#AFIRSTNAME",
    familyNameAr: "#AFAMILY",
    thirdNameAr: "#AGRAND",
    secondNameAr: "#AFATHER",
    firstNameEn: "#EFIRSTNAME",
    fatherNameEn: "#EFATHER",
    grandFatherNameEn: "#EGRAND",
    familyNameEn: "#EFAMILY",
    passportNumber: "#PASSPORTnumber",
    birthPlace: "#BIRTH_PLACE",
    passportIssuePlace: "#PASSPORT_ISSUE_PLACE",
    profession: "#JOB_OR_RELATION",
    degree: "#DEGREE",
    degreeSource: "#DEGREE_SOURCE",
    addressHome: "#ADDRESS_HOME",
    passportType: "#PASSPORType",
    nationalityFirst: "#NATIONALITY_FIRST",
    religion: "#RELIGION",
    socialStatus: "#SOCIAL_STATUS",
    sex: "#Sex",
    personId: "#PersonId",
    passportIssueDate: "#PASSPORT_ISSUE_DATE",
    passportExpiryDate: "#PASSPORT_EXPIRY_DATe",
    birthDate: "#BIRTH_DATE",
    expectedEntryDate: "#ExpectedEntryDate",
    personalImage: "#PersonalImage",
    noPreviousNationality: "#myform > div.form-body.form-horizontal > fieldset:nth-child(3) > div > div:nth-child(5) > div.col-md-3 > label:nth-child(2)",
    noPreviousTravel: "#myform > div.form-body.form-horizontal > fieldset:nth-child(5) > div > div:nth-child(25) > div > div > label:nth-child(2)",
    allInformationCorrect: "#myform > div.form-body.form-horizontal > fieldset:nth-child(5) > div > div:nth-child(28) > div > label",
    agreeToTerms: "#IsPrivacyPolicyAgreed",
    submit: "#btnSubmit",
    saveButton: "#myform > div.form-actions.fluid.right > div > div > button",
    captchaImage: "#imgCaptcha",
    captchaInput: "#Captcha",
    captchaError: "#myform > div:nth-child(3)",
    email: "#Personal_Email",
    carrier: "#COMING_THROUGH",
    visaIssuedNumber: "#DocumentNumber",
    sponsorId: "#SPONSER_NUMBER",
    sponsorPhone: "#SPONSER_PHONE",
    sponsorName: "#SPONSER_NAME",
    purpose: "#porpose",
    sponsorAddress: "#SPONSER_ADDRESS",
    carNumber: "#car_number",
    entryPoint: "#ENTRY_POINT",
    docError: "#divDocError",
    docError1: "#myform > div:nth-child(3)",
    returnButton: "#myform > div.form-actions.fluid.right > div > div > a",
    headerNav: "body > div.dga-header-wrapper > header > nav",
  },
};

module.exports = { SELECTORS };
