name: verification

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  microsoft_install:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [22.x] # Use Node.js 22

    steps:
    - uses: actions/checkout@v2

    # Set up Node.js 22.x
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Install dependencies
    - name: Install dependencies
      run: npm ci

    # Verify Node.js version
    - name: Verify Node.js version
      run: node -v

    # Run your script (replace 'node .' with your actual command)
    - name: Run script
      run: node . # Adjust this to the script/command you want to execute
